# Paths
reads_dir: "data"
results_dir: "results"
# Coverage threshold for post-IRMA steps
coverage_min_depth: 50

#porechop memory
porechop_mem_mb: 80000
porechop_time_min: 720


# IRMA container image
# Recommended: pin a digest for reproducibility. If you don't have one yet,
# keep :latest for now and update later to a sha256-digest.
irma_image: "docker://ghcr.io/cdcgov/irma:latest"
# irma_image: "docker://ghcr.io/cdcgov/irma@sha256:PUT_YOUR_PINNED_DIGEST_HERE"
